### PR TITLE
Fix/6042 fix duplicated plans

### PR DESCRIPTION
**Pull request by marcambier**
https://github.com/gravitee-io/issues/issues/6042

This fixes multiple bugs on API import and duplication processes.

**Known bugs :**
- when you export an API, then import it during the "create api" feature, it creates a duplicated plan in the api definition (but not in plan table)
- when you duplicate an API, it creates a duplicated plan in the api definition (but not in plan table)
- when you export an API, then import it on the same API, it creates a duplicated plan in the plan table
- when you export an API, add plan to it, then import it on the same API. Additional plans will not be removed in plan table (but will be removed from api definition)

**We have to ensure we cant produce any inconsistency between api.definition.plans and plans table.
All possible import actions should result with api.definition.plans == plans table, and do not produce any plan duplication.**

Those fixes are workarounds, we have to completely refactor the way we stores plans on 3.13, and stop this duplication between api.definition.plans / plans table (see https://github.com/gravitee-io/issues/issues/6054).

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/fix-6042-fix-duplicated-plans/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

**Review by gcusnieux — COMMENTED** [review]
Be carful, I think it's more complex. This behavior should be implement only for V2 apis.

**Comment by marcambier** [comment]
> Be carful, I think it's more complex. This behavior should be implement only for V2 apis.

As discussed together, it looks good to me
Because when you export a V1 API, the json file contains plans, event if there are not in API definition.

**Review by ytvnr — APPROVED** [review]

**Review by gaetanmaisse — APPROVED** [review]
Great job @marcambier, API Promotion is working great

**Pull request merged**
