### PR TITLE
feat(cert): support for auto reload certificate when updated

### LINKED ISSUE #5888: [platform] Auto-renew certificates
Instead of having to restart the HTTP server nodes to handle certificate renewal, it would be better to add listeners for automatic certificates reload.

This is true when:
- The truststore / keystore is / are based on a file from the filesystem
- The truststore / keystore are based on kubernetes secrets / TLS (thanks to https://github.com/gravitee-io/issues/issues/5887)

### PR DESCRIPTION
**Pull request by ThibaudAV**
Moved from : https://github.com/gravitee-io/gravitee-gateway/pull/786 
---

**Issue**

Closes gravitee-io/issues#5888

**Description**

Support file base and kubernetes configuration.

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-hlpspvbkkl.chromatic.com)

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-5888-certificate-auto-reload/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

**Comment by ThibaudAV** [comment]
IMHO - todo : rebase this PR https://github.com/gravitee-io/gravitee-node/pull/89 and change gravitee-node version in this PR one

**Comment by gaetanmaisse** [comment]
Replaced by https://github.com/gravitee-io/gravitee-api-management/pull/879

**Pull request closed without merging**
