### PR TITLE
refactor: remove deprecated endpoints

### PR DESCRIPTION
**Pull request by a-cordier**
BREAKING CHANGE:

The following resources were deprecated since version 3.12.0 and no longer exist starting from version 3.15.0

  - PUT /apis/{api.id}/keys/{apiKey.key}
  - DELETE /apis/{api.id}/keys/{apiKey.key}
  - POST /apis/{api.id}/keys/_verify?apiKey={apiKey.key}
  - POST /apis/{api.id}/keys/_verify?apiKey={apiKey.key}
  - GET /apis/{api.id}/subscriptions/{subscription.id}/keys
  - POST /apis/{api.id}/subscriptions/{subscription.id}
  - POST /apis/{api.id}/subscriptions/{subscription.id}/keys/{apiKey.key}/_reactivate
  - GET /applications/{application.id}/subscriptions/{subscription.id}/keys
  - POST /applications/{application.id}/subscriptions/{subscription.id}
  - DELETE /applications/{application.id}/subscriptions/{subscription.id}/keys/{apiKey.key}

see https://github.com/gravitee-io/issues/issues/6144

### CODE REVIEW

**Review by marcambier — COMMENTED** [review]
Should we add something about that in the 3.15 upgrade note ?

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-yzeonyzics.chromatic.com)

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/6144-refactor-remove-deprecated-endpoints/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

**Comment by a-cordier** [comment]
> Should we add something about that in the 3.15 upgrade note ?

see https://github.com/gravitee-io/release/pull/407/files

**Comment by gaetanmaisse** [comment]
Replaced by https://github.com/gravitee-io/gravitee-api-management/pull/889

**Pull request closed without merging**
