### PR TITLE
Portal: Display api owner 

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**

gravitee-io/issues#6485

**Description**

- [x]  to merge after this PR : https://github.com/gravitee-io/gravitee-ui-components/pull/507

**Additional context**

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-almotoatiq.chromatic.com)

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/507-display-owner/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-hyuhopataa.chromatic.com)

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/507-display-owner/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

**Review by gcusnieux — APPROVED** [review]

**Review by gaetanmaisse — APPROVED** [review]

**Comment by gaetanmaisse** [comment]
⚠️  DO NOT MERGE before 3.14 has been released

**Comment by gaetanmaisse** [comment]
Replaced by https://github.com/gravitee-io/gravitee-api-management/pull/866

**Pull request closed without merging**
