### PR TITLE
feat: support webhook on api update and deploy events

### PR DESCRIPTION
**Pull request by ytvnr**
**Issue**

https://github.com/gravitee-io/issues/issues/5426

**Description**

- Add Deploy and Update event for an API
- Reword API-key label in `APIHook` to have them well ordered in the UI
- Add templates for the new events
- remove some dead code in `ApiServiceImpl` which is duplicated in `ApiDuplicatorServiceImpl`

### CODE REVIEW

**Review by phiz71 — APPROVED** [review]

**Comment by phiz71** [comment]
Wait for the merge of the console in the monorepo before merging this PR

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-rfnxufixtu.chromatic.com)

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-5426-webhook-api-update-deploy-events/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-jadyggbaqi.chromatic.com)

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/issues-5426-webhook-api-update-deploy-events/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

**Pull request merged**
