### PR TITLE
Change FROM image in Dockerfiles

### PR DESCRIPTION
**Pull request by mhuzkhan**
We are migrating to `eclipse-temurin:11-jre-focal` as it provides better security then the `openjdk:11-jre-slim-buster` FROM image.

 Additionally, we are using versioned FROM images i.e. Alpine.

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-qkdpbfwpll.chromatic.com)

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/cicd-snyk-vulnerabilities/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

**Review by gaetanmaisse — APPROVED** [review]
✅  LGTM for the `Dockerfile-dev`, waiting for a double-check of @brasseld  for the `eclipse-temurin:11-jre-focal` move

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://612657caa8e859003a8a6430-hccncraekk.chromatic.com)

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/cicd-snyk-vulnerabilities/index.html)! 🚀

_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

**Pull request merged**
